In [1]:
import pandas as pd

df = pd.read_csv('metaData.csv')
df

,column_name,description,type,notes
0,id_cliente,Identificador único del cliente,int,Un cliente puede aparecer en varios meses y si...
1,mes,Mes calendario en formato AAAAMM,int,El split temporal se realiza por ventana mensu...
2,edad,Edad del cliente,int,Variable numérica
3,ingresos,Ingresos anuales,float,Variable numérica
4,ratio_deuda_ingresos,Ratio de deuda sobre ingresos,float,Variable numérica
5,antiguedad_cuenta_meses,Antigüedad de la cuenta del cliente en meses,int,Variable numérica
6,numero_productos,Número de productos bancarios activos del cliente,int,Variable numérica
7,saldo_promedio,Saldo promedio de la cuenta,float,Variable numérica
8,dias_ultima_transaccion,Días desde la última transacción,int,Variable numérica
9,ocupacion,Categoría laboral del cliente,string,Variable categórica
10,region,Región del cliente,string,Variable categórica
11,canal_adquisicion,Canal por el que el cliente fue adquirido,string,Variable categórica
12,banda_riesgo,Segmento de riesgo del cliente,string,Variable categórica
13,dias_ultima_interaccion,Días desde la última interacción registrada co...,int,Variable numérica
14,tiene_tarjeta_credito,Indica si el cliente tiene tarjeta de crédito,boolean,Flag binaria
15,activo_movil,Indica si el cliente está activo en la app móvil,boolean,Flag binaria
16,es_nuevo_cliente,Indica si el cliente es nuevo,boolean,Flag binaria
17,tiene_prestamo,Indica si el cliente tiene un préstamo activo,boolean,Flag binaria
18,antiguedad_direccion_meses,Antigüedad de la dirección registrada en meses,int,Variable numérica
19,visitas_web_ultimos_90_dias,Número de visitas web en los últimos 90 días,int,Variable numérica
20,distancia_sucursal_km,Distancia aproximada a la sucursal más cercana,float,Variable numérica
21,dispositivo_principal,Dispositivo principal registrado,string,Variable categórica
22,dia_preferido_pago,Día preferido del mes para realizar pagos,int,Variable numérica
23,tiene_seguro,Indica si el cliente tiene un seguro contratado,boolean,Flag binaria
24,objetivo,Etiqueta objetivo de primera conversión en ese...,boolean,Disponible solo en train y en la versión con e...
25,prediccion,Probabilidad de predicción del modelo,float,Columna requerida en la entrega; debe estar en...

In [2]:
df.sort_values(by='column_name')

,column_name,description,type,notes
15,activo_movil,Indica si el cliente está activo en la app móvil,boolean,Flag binaria
5,antiguedad_cuenta_meses,Antigüedad de la cuenta del cliente en meses,int,Variable numérica
18,antiguedad_direccion_meses,Antigüedad de la dirección registrada en meses,int,Variable numérica
12,banda_riesgo,Segmento de riesgo del cliente,string,Variable categórica
11,canal_adquisicion,Canal por el que el cliente fue adquirido,string,Variable categórica
22,dia_preferido_pago,Día preferido del mes para realizar pagos,int,Variable numérica
13,dias_ultima_interaccion,Días desde la última interacción registrada co...,int,Variable numérica
8,dias_ultima_transaccion,Días desde la última transacción,int,Variable numérica
21,dispositivo_principal,Dispositivo principal registrado,string,Variable categórica
20,distancia_sucursal_km,Distancia aproximada a la sucursal más cercana,float,Variable numérica
2,edad,Edad del cliente,int,Variable numérica
16,es_nuevo_cliente,Indica si el cliente es nuevo,boolean,Flag binaria
0,id_cliente,Identificador único del cliente,int,Un cliente puede aparecer en varios meses y si...
3,ingresos,Ingresos anuales,float,Variable numérica
1,mes,Mes calendario en formato AAAAMM,int,El split temporal se realiza por ventana mensu...
6,numero_productos,Número de productos bancarios activos del cliente,int,Variable numérica
24,objetivo,Etiqueta objetivo de primera conversión en ese...,boolean,Disponible solo en train y en la versión con e...
9,ocupacion,Categoría laboral del cliente,string,Variable categórica
25,prediccion,Probabilidad de predicción del modelo,float,Columna requerida en la entrega; debe estar en...
4,ratio_deuda_ingresos,Ratio de deuda sobre ingresos,float,Variable numérica
10,region,Región del cliente,string,Variable categórica
7,saldo_promedio,Saldo promedio de la cuenta,float,Variable numérica
17,tiene_prestamo,Indica si el cliente tiene un préstamo activo,boolean,Flag binaria
23,tiene_seguro,Indica si el cliente tiene un seguro contratado,boolean,Flag binaria
14,tiene_tarjeta_credito,Indica si el cliente tiene tarjeta de crédito,boolean,Flag binaria
19,visitas_web_ultimos_90_dias,Número de visitas web en los últimos 90 días,int,Variable numérica